spring: 
    profiles:
        active: dev

---
#开发环境配置
spring: 
  profile: dev
  application: 
    name: user-customer
server:
    port: 9004
### Feign 配置
feign:
  hystrix:
        enabled : true 
  httpclient:
        enabled: true
  
  # 开启断路器（熔断器）
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
security: 
  oauth2: 
    client: 
     client-id: client
     client-secret: secret
     access-token-uri: http://localhost:3001/oauth/token
     user-authorization-uri: http://localhost:3001/oauth/authorize
    resource: 
      prefer-token-info: true
      token-info-uri: http://localhost:3001/oauth/check_token

eureka:
  instance:
    hostname: user-customer.com 
    instance-id: user-customer  #集群配置 这里要不同
    prefer-ip-address: true   # 访问路径可以ip 显示
  client:
    service-url:
      #defaultZone: http://eurka01.com:8761/eureka,http://eurka02.com:8764/eureka,http://eurka03.com:8765/eureka     #集群配置
      defaultZone: http://eurka01.com:7001/eureka
      #register-with-eureka: false
info:   #追加微服务 信息 
  app.name: user-service
  company.name: www.zjx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

    
    
    
    
